Added in neopaeds logic to all scripts and subsequently changed the s…
nhs-england-patient-safety/patient-safety-data-request-template pull request #17
Opened 2024-11-04 10:32 UTC by Mattlikescoding

…tructure a bit

2024-11-04 10:33 UTC, Mattlikescoding commented
Added neopaeds logic to NRLS LFPSE and StEIS scripts, the flow has been changed a bit to accommodate the logic

2024-11-11 22:25 UTC, joshuamutio requested changes
Good job Matt. Some changes suggested. A general comment: you could probably make this a bit nicer to read by making your text search column earlier, and by creating a case_when column which runs through the conditions, then filtering last based on what was passed to params. E.g.:
```
lfpse_neopaeds = case_when(
age is < 28 days ~ 'neonate_by_age',
(age == 0 | is.na(age))  & specialty %in% neonatal_specialties ~ 'neonate_by_specialty',
(age == 0 | is.na(age)) & str_detect(text_search_columns, neonate_strings) ~ 'neonate_by_text')
)
```

then you would follow that with
```
 if(neopaeds = 'neonates'){
filter(str_detect(lfpse_neopaeds, 'neonate')
}

```

and repeat for paeds etc

2024-11-11 22:25 UTC, joshuamutio commented on lfpse.R
> +          is.na(P004_days) & is.na(P007) &
You can remove 139-150 by simply adding this as another condition to line 126

2024-11-11 22:25 UTC, joshuamutio commented on lfpse.R
> +            is.na(P004_days) | is.na(P007)
As above

2024-11-11 22:25 UTC, joshuamutio commented on lfpse.R
> +      # First condition: Age between 0 and 3 months and PD04 must be pediatric if age is 0
Isn't this for neonates?

2024-11-11 22:25 UTC, joshuamutio commented on lfpse.R
> +        (P004_days > 0 & P004_days < 6575) | (P007 > "D0" & P007 < "Y18")
Shouldn't this be 3 months - 18 y? Also be careful with conversion factors - LFPSE uses 31 days for months and 372 days for years (but we know some aren't doing this)

2024-11-11 22:25 UTC, joshuamutio commented on lfpse.R
> +          (P004_days == 0 | P007 == "D0") &
Are you sure this is right? It looks like D0 is used only in NRLS but I could be wrong

2024-11-11 22:25 UTC, joshuamutio commented on steis.R
> +# Neonate Search
Did we used to run a neopaeds for StEIS in the NRLS days?

2024-11-11 22:25 UTC, joshuamutio commented on steis.R
> +                  !grepl("(?i)\\badult|\\bold|\\belderly|\\bgeriat", paste(care_sector_other, clinical_area_other, type_of_incident_other, sep = ""))
Can you check this isn't pulling any young person specialties by accident e.g. 'young adult'

2024-11-11 22:25 UTC, joshuamutio commented on steis.R
> +steis_neonate <- steis_filtered_text |>
call this neopaed not neonate as you did for lfpse and nrls

2024-11-11 22:25 UTC, joshuamutio commented on steis.R
> +    (patient_age_years < 18)
don't we need a lower bound as well i.e. older than neonates?

2024-11-26 09:20 UTC, Mattlikescoding commented
Amended logic and corrected based on comments above

2025-01-17 12:54 UTC, ruth-keane-nhs commented
Made discussed changes

2025-03-17 13:15 UTC, ruth-keane-nhs commented
Closing this pull request because it is significantly out of date now- up to date neopaeds pull request is here https://github.com/nhs-england-patient-safety/patient-safety-data-request-template/pull/36

2025-03-17 13:15 UTC, closed without merging